name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dummy env files
        run: |
          touch .env.dev
          touch .env.prod
          touch .env.prod.db

      - name: Build images
        run: docker compose up -d --build

      - name: Check running containers
        run: docker compose ps
